USE [Elsi_T3]
GO

/****** Object:  View [dbo].[rojTemp4Judy]    Script Date: 03/25/2018 23:22:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[vw_ManagersForOSHENS]
AS

SELECT DISTINCT
m.MAN_ID,
EMPLOYEE_ID,
SURNAME,
FAMILIAR_NAME,
CASE
			WHEN u1.MAN_ID IS NOT NULL
				THEN 1
				ELSE NULL       
			END AS 'OD',
CASE
			WHEN u2.MAN_ID IS NOT NULL
				THEN 1
				ELSE NULL       
			END AS 'CSM',
CASE
			WHEN pm.MAN_ID IS NOT NULL
				THEN 1
				ELSE NULL       
			END AS 'TL',
CASE
			WHEN pm2.MAN_ID IS NOT NULL
				THEN 1
				ELSE NULL       
			END AS 'PS',
CASE
			WHEN u3.MAN_ID IS NOT NULL
				THEN 1
				ELSE NULL       
			END AS 'MAN'
FROM MANAGERS m
LEFT JOIN PROJECT_MEMBERS pm ON pm.MAN_ID = m.MAN_ID AND pm.PMR_CODE = 'TL'
LEFT JOIN PROJECT_MEMBERS pm2 ON pm2.MAN_ID = m.MAN_ID AND pm2.PMR_CODE = 'PS'
LEFT JOIN UNIT u1 ON u1.MAN_ID = m.MAN_ID AND u1.CURRENT_IND = 1 AND u1.LEVEL = 3 AND u1.CS_UNIT = 1
LEFT JOIN UNIT u2 ON u2.MAN_ID = m.MAN_ID AND u2.CURRENT_IND = 1 AND u2.LEVEL = 4 AND u2.CS_UNIT = 1
LEFT JOIN UNIT u3 ON u3.MAN_ID = m.MAN_ID AND u3.CURRENT_IND = 1 AND u3.CS_UNIT = 0
WHERE EMPLOYEE_ID IS NOT NULL
AND (pm.MAN_ID IS NOT NULL OR pm2.MAN_ID IS NOT NULL OR u1.MAN_ID IS NOT NULL OR u2.MAN_ID IS NOT NULL OR u3.MAN_ID IS NOT NULL)

GO


